### ISSUE TITLE
Converting AFV from numeric to character and back again

### ISSUE THREAD

**Issue by pet221** [michaeldumelle/SSN2temp2#10]
We need to preserve the maximum possible precision in the additive function values to ensure that we get positive definite covariance matrices. Some of these values can be very small - especially when networks are large with many edge segments. This is why we decided to convert the numbers  to character. However, I've realised that the function as.character is not preserving those decimal places. See description of issue here: https://stackoverflow.com/questions/64131808/can-as-numericas-characterx-where-x-is-originally-a-numeric-ever-change-x 

However, it does work as expected if we use formatC: to convert from numeric to character: 

ssn<- import_ssn(filepath = "C:/temp/lsndata/MiddleFork04.ssn",
                 predpts = c("Knapp", "pred1km", "CapeHorn"),
                 o.write = TRUE)
obs.df<- ssn$obs

WORKS!!! CONVERT NUMERIC WITH FULL PRECISION TO CHARACTER WITHOUT TRAILING 0'S :)
test2 <- formatC(obs.df$afvArea, digits = 254, format = "f",
                 drop0trailing = TRUE)

You can simply use as.numeric()  to convert these values to numeric with full precision. HOWEVER, you must use formatC (as demonstrated above). I suggest making a copy of the additive function value in numeric format. If you do converte the original column to numeric, you will need to convert it back to character using formatC (as demonstrated above) before exiting the function. 

I had a look at some of your functions in SSN2temp2 and couldn't see where the conversion was happening - which function is it? Or does it still need to be implemented?

I'm a bit worried about this process  - I would feel better if we talked through the workflow in more detail.

**Comment by michaeldumelle** [comment]
The only time I mess with the additive function value is on lines 284-288 of get_dist_object.R, and all I am doing is converting the character vector in the data to a numeric vector. So this should work and preserve the proper digits with full precision. Happy to talk more Wednesday!

**Comment by pet221** [comment]
Assuming that you're fitting a model, is the afv column in the model$ssn.object returned as numeric or character? It should be returned as character, with the full precision. The safest way IMO is to make a copy of it, which is converted to numeric so that the original never gets changed.  Or you could convert it back using formatC before returning the fitted model.

**Comment by michaeldumelle** [comment]
It is returned as a character with full precision. I never actually edit the afv column within the data set when fitting the model. I just pull out the column (i.e., make a copy), store it locally, convert it to numeric, and use it to create the "w" matrix.
