### ISSUE TITLE
ssn_glm with no prediction sites returns weird ssn.object$preds structure

### ISSUE THREAD

**Issue by pet221** [michaeldumelle/SSN2temp2#4]
In an SSN object that does not include prediction sites the first element in the ssn.object$preds == NA, but the length(ssn.object$preds) == 1.  When a model is fit to this SSN object a new data.frame ".missing" is added as the *second* element in ssn.object$preds, when it should be the first. The names of the new ssn.object$preds are then c(" ", ".missing"). I've gone back and modified the import_ssn function so that an SSN object without prediction sites returns an empty list (with length ==0) for ssn.object$preds. This fixes this issue, but I don't know if it will cause new issues for other functions?

However, I also noticed that an SSN object with no missing response values still returns a prediction set named ".missing", but it's dimensions are 0 x ncol(obs). So the question is - should the ".missing" prediction dataset be returned when there are no missing response values? 

Also, ".missing" does not contain any data - it's just full of NAs. I believe it should contain a subset of the original ssn.object$obs data.frame that has missing response values, so that the user can make predictions at those missing observed locations/times? 

To recreate the issue
`copyLSN2temp()`

Create an SSN object that does not contain prediction points
`mf04` <- import_ssn(paste0(tempdir(),'/MiddleFork04.ssn'),  o.write = TRUE)

Fit model
`ssngmod` <- ssn_glm(Summer_mn ~ netID, mf04, family = "Gamma", additive = "afvArea")

Look at preds ".missing"
`names(ssngmod$ssn.object$preds)`
dim(ssngmod$ssn.object$preds[[1]])
dim(ssngmod$ssn.object$obs)

**Comment by michaeldumelle** [comment]
Thanks. I edited the code to only return the `.missing` object when there is at least one datum in the `obs` data set that has a missing response value requiring prediction. In this code, I also create the `preds` object if there is not one, so you should not have to create the empty list in the `import_ssn` function. You can close the issue once you revert the "empty list" part of `import_ssn`.

See commit ed1d928d9abcb861a8af25f6510eb2103d09b837

**Comment by pet221** [comment]
I think iI'd rather have an empty list for preds when they're not present - it makes more sense to me because preds is actually a list of sf data.frames (when data are present). If I don't change it back to NA, how much work does that cause you?

**Comment by michaeldumelle** [comment]
No work for me -- my code works either way. Happy with whatever you decide. Closing the issue.
