### ISSUE TITLE
plot SSN object

### ISSUE THREAD

**Issue by pet221** [michaeldumelle/SSN2temp2#5]
Currently don't have a plotting function for an SSN object, only fitted model objects. Should we have a built in function? If we do, I assume the generic function would be plot.SSN or plot.ssn - does this create a conflict with plot.ssn_lm? I notice that the @name there is plot.ssn, but I'm not sure what the ramifications are of that.

**Comment by michaeldumelle** [comment]
This won't create a conflict with `plot.ssn_lm`. For `spmodel`, I made all function documentation for various generics easy to find by including it all in a `plot.spmodel` documentation object (so users get all documentation by simply remembering `function_name.spmodel`. We can have the plotting generic be `plot.SSN` and the documentation "catch-all" be `function_name.SSN2`? Or is there another solution you prefer?

**Comment by pet221** [comment]
You have a lot more experience creating generics than I do, so I'll let you
decide. :)

**Comment by pet221** [comment]
We may need some kind of catch-all for print as well.

**Comment by michaeldumelle** [comment]
Ok thanks I will feel it out and make a call.
