### ISSUE TITLE
plot linear and generalized linear model objects

### ISSUE THREAD

**Issue by michaeldumelle** [michaeldumelle/SSN2temp2#6]
In `spmodel`, it is straightforward to plot the empirical covariance vs distance:

```r
library(spmodel)
spmod <- splm(sulfate ~ 1, sulfate, spcov_type = "exponential")
plot(spmod, which = 7)
```
Do we want some sort of plot(s) in `SSN2`? It is not straightforward how to proceed given the nature of flow-connected vs flow-unconnected distance. For example, if there is a taildown covariance, do we make separate plots for flow-connected vs flow-unconnected covariances?

**Comment by pet221** [comment]
We combined the flow-connected and flow-unconnected covariances within a single SSN Torgegram, with the x-axis representing hydrologic distance (ignoring directionality). Could we do the same with Euclidean distance? In that case, the spatial relationship (flow-connected, flow-unconnected, and Euclidean) would define how the distance is measured (different lines), but the x-axis simply represents distance in some common unit like meters.  Also, are you planning on including the empirical semivariogram (i.e. Torgegram)? It would be sad to see it go and it seems like a lot of people  use it :)

**Comment by michaeldumelle** [comment]
Yes the `Torgegram()` and `plot.Torgegram()` are up and running . But if we want to show "taildown" covariance as a function of "distance", for example, I am not sure how to do that cleanly, as the taildown covariance has parts contributing from both the flow-unconnected and flow-connected networks.

**Comment by michaeldumelle** [comment]
Jay and I talked about this and have some ideas. We could show observed data empirical covariance for tailup and taildown covariances for all pairs of data, similar to the "fitted semivariogram" points from Figure 7 of the JASA stream networks paper. However, this may not make it into the initial release.

**Comment by pet221** [comment]
I'm glad you discussed it with him and the fitted semivariogram would be great. I also don't think it's a big deal if it isn't in the first version.
