### ISSUE TITLE
extract_netgeom format

### ISSUE THREAD

**Issue by pet221** [michaeldumelle/SSN2temp2#8]
extract_netgeom currently returns a data.frame with columns (netID, rid, upDist, ratio, pid, locID) in character format. They should probably be converted to numeric to match what is contained in obs, edges, and each of the preds. How will this affect your functions - any objections? 

Update: I've added an argument, reformat,  for converting to numeric that is set to FALSE as the default. It *shouldn't* affect what's currently returned in  your code.

**Comment by michaeldumelle** [comment]
Sounds good! Also, the numeric conversion should not affect anything on my end.
